contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #testtoweraws channel"
    url: https://nfcore.slack.com/channels/testtoweraws
    about: Discussion about the nf-core/testtoweraws pipeline
